import type { TowerSnapshot } from "./domain";

export const fixtureSnapshot: TowerSnapshot = {
  generatedAt: "2026-08-19T03:42:00Z",
  viewerName: "Lucas",
  workspaceName: "nilor.cool",
  source: "fixture",
  channels: [
    {
      id: "mos-boston",
      name: "mos-boston",
      description: "Museum of Science Boston deployment",
      workstreams: [
        {
          id: "museum-install",
          title: "Museum bridge rollout",
          phase: "Install readiness",
          agents: [
            {
              id: "dany-loop",
              agentName: "dany-mos-agent",
              role: "Implementation",
              status: "working",
              statusLabel: "Working",
              operation: "Validating the Bloodline → Topaz → Disguise loop",
              elapsed: "18m 42s",
              lastActivity: "8s ago",
              model: "gpt-5.6-sol · high",
              branch: "feat/bloodline-upscale",
              head: "93bd10c",
              helperCount: 2,
              activity: [
                {
                  id: "a1",
                  at: "03:41:52",
                  kind: "tool",
                  title: "Running integration test",
                  detail: "Bloodline generation completed; waiting on Topaz upscale output.",
                  status: "running",
                },
                {
                  id: "a2",
                  at: "03:39:18",
                  kind: "evidence",
                  title: "Commit created",
                  detail: "93bd10c · add HAP output validation and timeout recovery",
                  status: "complete",
                },
                {
                  id: "a3",
                  at: "03:35:06",
                  kind: "tool",
                  title: "Inspected container logs",
                  detail: "Confirmed the generation worker returned a valid source frame sequence.",
                  status: "complete",
                },
                {
                  id: "a4",
                  at: "03:23:10",
                  kind: "lifecycle",
                  title: "Turn started",
                  detail: "Triggered from the museum-install workstream.",
                  status: "complete",
                },
              ],
              context: [
                {
                  id: "c1",
                  kind: "base",
                  label: "Buzz platform context",
                  detail: "Session model, messaging rules, workspace conventions",
                  hash: "e97c…41a2",
                  size: "8.4 KB",
                  visibility: "provenance",
                },
                {
                  id: "c2",
                  kind: "thread",
                  label: "Museum bridge rollout thread",
                  detail: "12 messages · newest agent reply pinned",
                  hash: "b402…f12c",
                  size: "14.7 KB",
                  visibility: "full",
                },
                {
                  id: "c3",
                  kind: "canvas",
                  label: "mos-boston canvas",
                  detail: "Revision 6158620f · metadata supplied, content fetched",
                  hash: "6158…9001",
                  size: "6.1 KB",
                  visibility: "full",
                },
                {
                  id: "c4",
                  kind: "repository",
                  label: "brain_rnd instructions",
                  detail: "AGENTS.md + deployment guide at HEAD de3bf366",
                  hash: "d30a…b51f",
                  size: "11.2 KB",
                  visibility: "provenance",
                },
              ],
              evidence: [
                { stage: "local", label: "Local changes", detail: "3 files", complete: true },
                { stage: "committed", label: "Committed", detail: "93bd10c", complete: true },
                { stage: "pushed", label: "Pushed", detail: "2m ago", complete: true },
                { stage: "pr-open", label: "Pull request", detail: "Not opened", complete: false },
                { stage: "merged", label: "Merged", detail: "Pending", complete: false },
                { stage: "deployed", label: "Deployed", detail: "Pending", complete: false },
              ],
              artifacts: [
                { id: "r1", kind: "code", name: "upscale-worker.ts", detail: "+86 −14", changedAt: "2m ago" },
                { id: "r2", kind: "code", name: "bloodline-loop.test.ts", detail: "+51 −3", changedAt: "3m ago" },
                { id: "r3", kind: "document", name: "SDD_PROGRESS.md", detail: "Checkpoint 7 updated", changedAt: "4m ago" },
              ],
            },
            {
              id: "mos-proxy",
              agentName: "mos-agent",
              role: "Architecture",
              status: "blocked",
              statusLabel: "Blocked",
              operation: "Waiting for production bridge network details",
              elapsed: "41m 09s",
              lastActivity: "6m ago",
              model: "gpt-5.6-sol · high",
              branch: "design/bridge-proxy",
              head: "6bd490a",
              helperCount: 0,
              activity: [
                { id: "m1", at: "03:36:01", kind: "message", title: "Blocker reported", detail: "Needs the museum bridge LAN addresses before the proxy contract can be finalized.", status: "failed" },
                { id: "m2", at: "03:21:42", kind: "tool", title: "Audited outbound endpoints", detail: "Mapped MinIO, SQS, LiveKit, Brain API, and content-display dependencies.", status: "complete" },
              ],
              context: [],
              evidence: [
                { stage: "local", label: "Local changes", detail: "Clean", complete: true },
                { stage: "committed", label: "Committed", detail: "6bd490a", complete: true },
                { stage: "pushed", label: "Pushed", detail: "31m ago", complete: true },
                { stage: "pr-open", label: "Pull request", detail: "Draft", complete: true },
                { stage: "merged", label: "Merged", detail: "Pending input", complete: false },
                { stage: "deployed", label: "Deployed", detail: "Pending", complete: false },
              ],
              artifacts: [],
            },
          ],
        },
        {
          id: "ui-polish",
          title: "Operator UI polish",
          phase: "Prototype",
          agents: [
            {
              id: "lucas-ui",
              agentName: "lucas-mos-agent",
              role: "Frontend",
              status: "idle",
              statusLabel: "Idle",
              operation: "Checkpoint saved; awaiting next instruction",
              elapsed: "—",
              lastActivity: "12m ago",
              model: "gpt-5.6-sol · high",
              branch: "feat/operator-layouts",
              head: "11f29bb",
              helperCount: 0,
              activity: [],
              context: [],
              evidence: [],
              artifacts: [],
            },
          ],
        },
      ],
    },
    {
      id: "buzz-control-tower",
      name: "buzz-control-tower",
      description: "Agent observability companion app",
      workstreams: [
        {
          id: "desktop-mvp",
          title: "Cross-platform desktop MVP",
          phase: "Foundation",
          agents: [
            {
              id: "fizz-control",
              agentName: "Lucas-Fizz",
              role: "Product engineering",
              status: "working",
              statusLabel: "Working",
              operation: "Building the fixture-driven Tauri application shell",
              elapsed: "07m 15s",
              lastActivity: "now",
              model: "gpt-5.6-sol",
              branch: "feat/desktop-mvp",
              head: "working tree",
              helperCount: 0,
              activity: [
                { id: "f1", at: "03:42:00", kind: "tool", title: "Scaffolding desktop shell", detail: "Tauri 2, React, Vite, TypeScript, and domain fixtures.", status: "running" },
              ],
              context: [],
              evidence: [
                { stage: "local", label: "Local changes", detail: "In progress", complete: true },
                { stage: "committed", label: "Committed", detail: "Pending", complete: false },
                { stage: "pushed", label: "Pushed", detail: "Pending", complete: false },
                { stage: "pr-open", label: "Pull request", detail: "Pending", complete: false },
                { stage: "merged", label: "Merged", detail: "Pending", complete: false },
                { stage: "deployed", label: "Deployed", detail: "Pending", complete: false },
              ],
              artifacts: [],
            },
          ],
        },
      ],
    },
    {
      id: "relay-ops",
      name: "relay-ops",
      description: "Buzz relay and hosted-agent operations",
      workstreams: [
        {
          id: "fleet-health",
          title: "Fleet health",
          phase: "Continuous",
          agents: [
            {
              id: "ops-health",
              agentName: "ops-agent",
              role: "Operations",
              status: "complete",
              statusLabel: "Healthy",
              operation: "Daily relay review complete",
              elapsed: "03m 08s",
              lastActivity: "2h ago",
              model: "gpt-5.6-sol · high",
              branch: "main",
              head: "7329f950",
              helperCount: 0,
              activity: [],
              context: [],
              evidence: [],
              artifacts: [],
            },
          ],
        },
      ],
    },
  ],
};
